# Site settings
baseURL = "https://mariekrainer.netlify.app/"
languageCode = "en-us"
title = "Portfolio website of Marie Krainer"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Marie-Therese Krainer"
  description = "Hello :)"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"



  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Portfolio Website"
    #subtitle = "By HTML5 Up"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Blogs"
      url = "blogs"

   # [[params.navigation.links]]
    #  name = "Generic Blog"
     # url = "blogs/ipsum"

   # [[params.navigation.links]]
    #  name = "Elements"
     # url = "elements.html"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "R Projects"
      url = "blogs"

    # Button Style 2
    #[[params.navigation.button2]]
      #name = "Log In"
      #url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, my name is Marie-Therese"
    subtitle = "This is me."
    buttonText = "Find out more"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Trump"
      subtitle = "Trump´s net approval rate"
      image = "trump_approval_margin.jpg"
      url = "blogs/aliquam"

    [[params.tiles.showcase]]
      title = "Brexit"
      subtitle = "Percentage of people voting to leave the EU by party"
      image = "brexit.png"
      url = "blogs/magna"
      
       [[params.tiles.showcase]]
      title = "Covid"
      subtitle = "death rate"
      image = "covid_death_rate_icu.jpg"
      url = "blogs/tempus"

    [[params.tiles.showcase]]
      title = "Trump vs. Clinton"
      subtitle = "Top 10 Californian cities that donated money"
      image = "challege2.png"
      url = "blogs/ipsum"


  [params.blog]


  # Section Type Two
  [params.two]
    enable = true
    title = "About Myself"
    subtitle = """Who I am. 
    My name is Marie and I am currently finishing my master´s degree in Analytics and Management
    at LBS. Before moving to London, I completed
    my undergraduate in information systems at the Technical University Munich. 
    Prior LBS I learned 
    programming languages such as Java, JavaScript, html, SQL and CSS. This portfolio, however, is my
    first attempt of R programming. Enjoy :)"""
    url = "blogs"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"
    formEmail = "mkrainer.mam2021@london.com"

    [[params.contact.email]]
    title = "Email"
    email = "mkrainer.mam2021@london.com"
    
        [[params.contact.phone]]
    title = "Phone"
    phone = "020 7000 7000"

    [[params.contact.address]]
    title = "London Business School"
    street = "Regent's Park"
    city = "London, NW1 4SA"
    country = "United Kingdom"

   

  # Footer section
  [params.footer]
    enable = true
    copyright = "Company Name"

    # Uses font awesome icons


    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/marie-therese-krainer/"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
