# Site settings
baseURL = "https://mariekrainer.netlify.app/"
languageCode = "en-us"
title = "Portfolio website of Marie Krainer"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Marie-Therese Krainer"
  description = "Hello :)"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Portfolio Website"
    #subtitle = "By HTML5 Up"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Projects"
      url = "projects"

   # [[params.navigation.links]]
    #  name = "Generic Blog"
     # url = "blogs/ipsum"

   # [[params.navigation.links]]
    #  name = "Elements"
     # url = "elements.html"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Learn more about what I have done so far"
      url = "projects"

    # Button Style 2
    #[[params.navigation.button2]]
      #name = "Log In"
      #url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, my name is Marie"
    subtitle = "This is me."
    buttonText = "Find out more"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Project One"
      subtitle = "Trump vs. Clinton"
      image = "pic01.jpg"
      url = "projects/one"

    [[params.tiles.showcase]]
      title = "Project Two"
      subtitle = "Challenge 2"
      image = "pic02.jpg"
      url = "projects/two"


  [params.blog]


  # Section Type Two
  [params.two]
    enable = true
    title = "About Myself"
    subtitle = """Who I am. 
    My name is Marie and I am currently finishing my master´s degree at LBS. Before that I completed
    my undergraduate at the Technical University Munich."""
    buttonText = "Find out more"
    url = "projects"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"
    formEmail = "mkrainer.mam2021@london.com"

    [[params.contact.email]]
    title = "Email"
    email = "mkrainer.mam2021@london.com"

   

  # Footer section
  [params.footer]
    enable = true
    copyright = "Company Name"

    # Uses font awesome icons


    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/marie-therese-krainer/"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
